M48
; DRILL file {KiCad 7.0.2} date Tue Aug  1 13:01:49 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-01T13:01:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X6.0686Y-2.035
X6.0686Y-3.3342
X7.9584Y-2.035
X7.9584Y-3.3342
T2
X7.8835Y-4.9496
X7.8835Y-5.3996
T0
M30
